// Generated by: node scripts/simplify-plr.js
// Source: Berlin LOR Planungsräume 2021 (CC BY 3.0 DE, AfS Berlin-Brandenburg)
// ViewBox: 0 0 85 104 (aspect-ratio corrected for lat ~52°)

export const PLR_VIEWBOX = '0 0 85 104';

export const PLR_PATHS: Record<string, string> = {
  '08100104': 'M65.8 47.4 L73.7 71.8 L44.6 77.2 L45 81.1 L32.7 83 L30.3 65.5 L34.6 59.8 L42.7 57.2 L41.3 51.9 L65.8 47.4 Z', // Wartheplatz
  '08100103': 'M23.1 20.9 L23.5 19.3 L25.9 20 L30.8 21.9 L31.4 25.3 L35.8 25.1 L38.6 37.7 L61.8 33.3 L65.8 47.4 L41.3 51.9 L42.7 57.2 L34.6 59.8 L30.3 65.5 L23.1 20.9 Z', // Schillerpromenade Süd
  '08100102': 'M2.9 2 L37.2 13.9 L55.3 10.8 L61.8 33.3 L38.6 37.7 L35.8 25.1 L31.4 25.3 L30.8 21.9 L23.5 19.3 L15.7 25.5 L3.8 23.3 L2 10.3 L2.9 2 Z', // Schillerpromenade Nord
  '08100105': 'M73.7 71.8 L82.9 94.8 L59.6 100.4 L47.2 101.1 L44.6 77.2 L73.7 71.8 Z', // Silbersteinstraße
};

export const PLR_CODES = Object.keys(PLR_PATHS);
