#!/usr/bin/env node
/**
 * One-time script: Simplifies Schillerkiez PLR GeoJSON polygons into SVG paths.
 * Zero dependencies — reads WGS84 GeoJSON, applies Douglas-Peucker simplification,
 * outputs TypeScript constants for plrPaths.ts.
 *
 * Usage: node scripts/simplify-plr.js
 * Input:  /tmp/schillerkiez_plr_wgs84.geojson
 * Output: stdout (paste into src/components/kiez/plrPaths.ts)
 *
 * Source: Berlin LOR Planungsräume 2021 (CC BY 3.0 DE, AfS Berlin-Brandenburg)
 */

import fs from 'fs';

const INPUT = '/tmp/schillerkiez_plr_wgs84.geojson';
const EPSILON = 1.2; // Douglas-Peucker tolerance in SVG units
const PADDING = 2;   // SVG padding for stroke visibility
const COS_LAT = Math.cos((52.47 * Math.PI) / 180); // ~0.61, corrects lng to ground distance

// --- Douglas-Peucker simplification ---
function perpendicularDist(p, a, b) {
  const dx = b[0] - a[0];
  const dy = b[1] - a[1];
  const lenSq = dx * dx + dy * dy;
  if (lenSq === 0) return Math.hypot(p[0] - a[0], p[1] - a[1]);
  const t = Math.max(0, Math.min(1, ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / lenSq));
  return Math.hypot(p[0] - (a[0] + t * dx), p[1] - (a[1] + t * dy));
}

function douglasPeucker(points, epsilon) {
  if (points.length <= 2) return points;
  let maxDist = 0, maxIdx = 0;
  for (let i = 1; i < points.length - 1; i++) {
    const d = perpendicularDist(points[i], points[0], points[points.length - 1]);
    if (d > maxDist) { maxDist = d; maxIdx = i; }
  }
  if (maxDist > epsilon) {
    const left = douglasPeucker(points.slice(0, maxIdx + 1), epsilon);
    const right = douglasPeucker(points.slice(maxIdx), epsilon);
    return left.slice(0, -1).concat(right);
  }
  return [points[0], points[points.length - 1]];
}

// --- Main ---
const geojson = JSON.parse(fs.readFileSync(INPUT, 'utf8'));
const features = geojson.features;

// Extract raw rings (first ring of first polygon of each MultiPolygon)
const plrs = features.map(f => ({
  code: f.properties.PLR_ID,
  name: f.properties.PLR_NAME,
  ring: f.geometry.coordinates[0][0], // [lng, lat] pairs
}));

// Compute combined bounding box
let minLng = Infinity, maxLng = -Infinity, minLat = Infinity, maxLat = -Infinity;
for (const plr of plrs) {
  for (const [lng, lat] of plr.ring) {
    if (lng < minLng) minLng = lng;
    if (lng > maxLng) maxLng = lng;
    if (lat < minLat) minLat = lat;
    if (lat > maxLat) maxLat = lat;
  }
}

// Ground-corrected dimensions
const groundW = (maxLng - minLng) * COS_LAT;
const groundH = maxLat - minLat;
const scale = 100 / Math.max(groundW, groundH); // fit into ~100 SVG units

const svgW = Math.round(groundW * scale) + 2 * PADDING;
const svgH = Math.round(groundH * scale) + 2 * PADDING;

// Convert geo coords to SVG coords
function toSvg(lng, lat) {
  const x = (lng - minLng) * COS_LAT * scale + PADDING;
  const y = (maxLat - lat) * scale + PADDING; // flip Y
  return [Math.round(x * 10) / 10, Math.round(y * 10) / 10];
}

// Process each PLR
const results = {};
for (const plr of plrs) {
  const svgPoints = plr.ring.map(([lng, lat]) => toSvg(lng, lat));
  const simplified = douglasPeucker(svgPoints, EPSILON);
  const d = simplified
    .map((p, i) => `${i === 0 ? 'M' : 'L'}${p[0]} ${p[1]}`)
    .join(' ') + ' Z';
  results[plr.code] = { name: plr.name, d, original: plr.ring.length, simplified: simplified.length };
}

// Output
console.log(`// Generated by: node scripts/simplify-plr.js`);
console.log(`// Source: Berlin LOR Planungsräume 2021 (CC BY 3.0 DE, AfS Berlin-Brandenburg)`);
console.log(`// ViewBox: 0 0 ${svgW} ${svgH} (aspect-ratio corrected for lat ~52°)\n`);
console.log(`export const PLR_VIEWBOX = '0 0 ${svgW} ${svgH}';\n`);
console.log(`export const PLR_PATHS: Record<string, string> = {`);
for (const [code, info] of Object.entries(results)) {
  console.log(`  '${code}': '${info.d}', // ${info.name} (${info.original} → ${info.simplified} pts)`);
}
console.log(`};\n`);
console.log(`export const PLR_CODES = Object.keys(PLR_PATHS);`);

// Summary to stderr
for (const [code, info] of Object.entries(results)) {
  process.stderr.write(`${code} ${info.name}: ${info.original} → ${info.simplified} points\n`);
}
